/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package easmbd;

import javax.swing.JFrame;

/**
 *
 * @author zary cecelya
 */

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class login extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    PreparedStatement pstat;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernamelog = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        passwordlog = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 239, 201));
        jPanel1.setPreferredSize(new java.awt.Dimension(1450, 740));

        jPanel2.setBackground(new java.awt.Color(20, 52, 75));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1450, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat datang,");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Silahkan masukkan Username dan Password");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easmbd/utrrlobt-removebg-preview.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        jButton2.setText("Login Sebagai Admin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(495, 495, 495)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(152, 152, 152)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernamelog, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(passwordlog))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(546, 546, 546))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usernamelog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(189, 189, 189)
                .addComponent(jButton2)
                .addGap(147, 147, 147))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String idKaryawan1 = null,
                idTim1 = null,
                namaKaryawan1 = null,
                alamatKaryawan1 = null,
                telpKaryawan1 = null,
                statusKaryawan1 = null,
                userKaryawan1 = null,
                hakAksesKaryawan1 = null,
                tglMasuk1 = null,
                idJabatan1 = null;
                
       //Hapus Session Admin
        String namaAdmin1 = null,
               hakAksesAdmin = null;
        adminSession.setNAMAADMIN(namaAdmin1);
                adminSession.setHAKAKSESADMIN(hakAksesAdmin);
        
        int idGaji1 = 0,
            umurKaryawan1 = 0;
                
        try {
             pstat = con.prepareStatement("SELECT * FROM karyawan INNER JOIN jabatan ON karyawan.IDJABATAN = jabatan.IDJABATAN INNER JOIN gaji ON karyawan.IDGAJI = gaji.IDGAJI INNER JOIN namatim ON karyawan.IDTIM = namatim.IDTIM WHERE USERKARYAWAN=? AND PASSWORDKARYAWAN=MD5(?);", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
             pstat.setString(1, usernamelog.getText());
             pstat.setString(2, passwordlog.getText());
             rs = pstat.executeQuery();
           while (rs.next()){
               idKaryawan1 = rs.getString("IDKARYAWAN");
               idTim1 = rs.getString("NAMATIM");
               namaKaryawan1 = rs.getString("NAMAKARYAWAN");
               telpKaryawan1 = rs.getString("TELPKARYAWAN");
               statusKaryawan1 = rs.getString("STATUSKARYAWAN");
               alamatKaryawan1 = rs.getString("ALAMATKARYAWAN");
               userKaryawan1 = rs.getString("USERKARYAWAN");
               hakAksesKaryawan1 = rs.getString("HAKAKSESKARYAWAN");
               tglMasuk1 = rs.getString("TGLMASUK");
               idGaji1 = rs.getInt("GAJIPOKOK");
               idJabatan1 = rs.getString("NAMAJABATAN");
               umurKaryawan1 = rs.getInt("UMURKARYAWAN");
               
            }
            rs.last();
            if (rs.getRow() == 1) {
                karyawanSession.setIDKARYAWAN(idKaryawan1);
                karyawanSession.setIDGAJI(idGaji1);
                karyawanSession.setIDJABATAN(idJabatan1);
                karyawanSession.setIDTIM(idTim1);
                karyawanSession.setNAMAKARYAWAN(namaKaryawan1);
                karyawanSession.setTELPKARYAWAN(telpKaryawan1);
                karyawanSession.setSTATUSKARYAWAN(statusKaryawan1);
                karyawanSession.setALAMATKARYAWAN(alamatKaryawan1);
                karyawanSession.setUSERKARYAWAN(userKaryawan1);
                karyawanSession.setHAKAKSESKARYAWAN(hakAksesKaryawan1);
                karyawanSession.setTGLMASUK(tglMasuk1);
                karyawanSession.setUMURKARYAWAN(umurKaryawan1);
                JOptionPane.showMessageDialog(null,"Berhasil Login");
                new main().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null,"Username atau Password salah!");
                passwordlog.setText(null);
                passwordlog.requestFocus();
            }
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String namaAdmin1 = null,
                hakAksesAdmin1 = null;
        
        //Hapus Session Karyawan
        String idKaryawan1 = null,
                idTim1 = null,
                namaKaryawan1 = null,
                alamatKaryawan1 = null,
                telpKaryawan1 = null,
                statusKaryawan1 = null,
                userKaryawan1 = null,
                hakAksesKaryawan1 = null,
                tglMasuk1 = null,
                idJabatan1 = null;
        int idGaji1 = 0,
                umurKaryawan1 = 0;
        karyawanSession.setIDKARYAWAN(idKaryawan1);
                karyawanSession.setIDGAJI(idGaji1);
                karyawanSession.setIDJABATAN(idJabatan1);
                karyawanSession.setIDTIM(idTim1);
                karyawanSession.setNAMAKARYAWAN(namaKaryawan1);
                karyawanSession.setTELPKARYAWAN(telpKaryawan1);
                karyawanSession.setSTATUSKARYAWAN(statusKaryawan1);
                karyawanSession.setALAMATKARYAWAN(alamatKaryawan1);
                karyawanSession.setUSERKARYAWAN(userKaryawan1);
                karyawanSession.setHAKAKSESKARYAWAN(hakAksesKaryawan1);
                karyawanSession.setTGLMASUK(tglMasuk1);
                karyawanSession.setUMURKARYAWAN(umurKaryawan1);
        
        try {
          pstat= con.prepareStatement("SELECT * FROM admin WHERE NAMAADMIN=? AND PASSWORDADMIN=MD5(?) ", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, usernamelog.getText());
          pstat.setString(2, passwordlog.getText());
           rs = pstat.executeQuery();
           while (rs.next()){
                namaAdmin1 = rs.getString("NAMAADMIN");
                hakAksesAdmin1 = rs.getString("HAKAKSESADMIN");
            }
            rs.last();
            if (rs.getRow() == 1) {
                adminSession.setNAMAADMIN(namaAdmin1);
                adminSession.setHAKAKSESADMIN(hakAksesAdmin1);
                JOptionPane.showMessageDialog(null,"Berhasil Login");
                new main().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null,"Username atau Password salah!");
                passwordlog.setText(null);
                passwordlog.requestFocus();
            }
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }                            
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passwordlog;
    private javax.swing.JTextField usernamelog;
    // End of variables declaration//GEN-END:variables
}
