/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package easmbd;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.batik.css.engine.value.StringValue;
import org.apache.commons.lang.RandomStringUtils;

/**
 *
 * @author zary cecelya
 */
public class Pelanggan extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    PreparedStatement pstat;
    ResultSet rs;
    String sql;
    
    String hakAksesAdminSET = adminSession.getHAKAKSESADMIN();
    String hakAksesKaryawan = karyawanSession.getHAKAKSESKARYAWAN();
    /**
     * Creates new form Pelanggan
     */
    public Pelanggan() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
       
//        gajiK.setText(String.valueOf(formatRupiah.format(idGajiSET)));
        
        
        hargaBarang.setEditable(false);
        nomorMerek.setVisible(false);
        nomorPem.setVisible(false);
        namabarangx.setVisible(false);
        nomorBX.setVisible(false);
        
        
        
         if ("Super Admin".equals(hakAksesAdminSET) || "Admin".equals(hakAksesAdminSET) || "Karyawan Tetap".equals(hakAksesKaryawan) || "Magang".equals(hakAksesKaryawan)) {
             hitung.setVisible(true);
           jButton3.setVisible(true);
        } else {
          hitung.setVisible(false);
           jButton3.setVisible(false);
        }
         
         
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        namaPembayaranBox();
        namaMerekBox();
    }
    
    public void namaPembayaranBox() {
      
        if ("Super Admin".equals(hakAksesAdminSET) || "Admin".equals(hakAksesAdminSET) || "Karyawan Tetap".equals(hakAksesKaryawan) || "Magang".equals(hakAksesKaryawan)) {
            try {
            String query = "{ call tampilTipePembayaran() }";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while (rs.next()) {                
                namaPembayaran.addItem(rs.getString("NAMAPEMBAYARAN"));
            }
            
            rs.last();
            int nomor = rs.getRow();
            rs.first();
           
        } catch (SQLException e) {
        }
        }
    }
    
    public void namaMerekBox() {
        if ("Super Admin".equals(hakAksesAdminSET) || "Admin".equals(hakAksesAdminSET) || "Karyawan Tetap".equals(hakAksesKaryawan) || "Magang".equals(hakAksesKaryawan)) {
            try {
            String query = "{ call tampilDetailMerek }";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while (rs.next()) {                
                namaMerek.addItem(rs.getString("NAMAMEREK"));
            }
            
            rs.last();
            int nomor = rs.getRow();
            rs.first();
           
        } catch (SQLException e) {
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaPelanggan = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hargaBarang = new javax.swing.JTextField();
        namaPembayaran = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        namaMerek = new javax.swing.JComboBox<>();
        kembali = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        nomorPem = new javax.swing.JTextField();
        namaBarang = new javax.swing.JComboBox<>();
        nomorMerek = new javax.swing.JTextField();
        namabarangx = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        nomorBX = new javax.swing.JTextField();
        nomorBX1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 239, 201));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 900));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(20, 52, 75));
        jPanel2.setPreferredSize(new java.awt.Dimension(70, 128));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Menu Pelanggan");

        jButton4.setText("Muat Ulang");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(513, 513, 513)
                .addComponent(jButton4)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jButton4))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setText("Nama Pelanggan");

        jLabel4.setText("Harga Barang/unit");

        jButton3.setText("Buat Pembayaran");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Merek Barang");

        jLabel8.setText("Jenis Pembayaran");

        hargaBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hargaBarangMouseEntered(evt);
            }
        });

        namaPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--" }));
        namaPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPembayaranActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easmbd/utrrlobt-removebg-preview.png"))); // NOI18N

        jLabel5.setText("Jumlah");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        jumlah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jumlahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jumlahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jumlahMouseExited(evt);
            }
        });

        namaMerek.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                namaMerekItemStateChanged(evt);
            }
        });
        namaMerek.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                namaMerekMouseMoved(evt);
            }
        });
        namaMerek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namaMerekMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                namaMerekMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                namaMerekMouseExited(evt);
            }
        });
        namaMerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaMerekActionPerformed(evt);
            }
        });

        kembali.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        jLabel11.setText("Nama Barang");

        namaBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namaBarangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                namaBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                namaBarangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                namaBarangMousePressed(evt);
            }
        });
        namaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaBarangActionPerformed(evt);
            }
        });
        namaBarang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                namaBarangPropertyChange(evt);
            }
        });
        namaBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                namaBarangKeyReleased(evt);
            }
        });

        total.setEditable(false);
        total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                totalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                totalMouseExited(evt);
            }
        });

        jLabel6.setText("Total");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        hitung.setText("Hitung");
        hitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hitungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hitungMouseExited(evt);
            }
        });
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        nomorBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorBXActionPerformed(evt);
            }
        });

        nomorBX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorBX1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Unit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(538, 538, 538)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaPelanggan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaPembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jumlah)
                                            .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nomorMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nomorBX, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nomorPem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(namabarangx, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomorBX1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)))))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(nomorPem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namabarangx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(namaMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomorMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomorBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomorBX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(hitung))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(64, 64, 64)
                .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
              Random ran = new Random();
              int x = ran.nextInt(6234233) + 2;
              int y = ran.nextInt(4234234) + 3;
              int z = ran.nextInt(1232312 + 2) + 1023 + (x + y);
              
              int barang = Integer.parseInt(nomorBX1.getText());
              int jumlah1 = Integer.parseInt(jumlah.getText());
              int hasil = barang-jumlah1;
        try {
            stat = con.createStatement();
            String SQL = "INSERT INTO pelanggan VALUES('"+z+"','"+nomorPem.getText()+"','"+nomorMerek.getText()+"','"+namaPelanggan.getText()+"', '"+namaBarang.getSelectedItem()+"', '"+hargaBarang.getText()+"', '"+jumlah.getText()+"')";
             String sql2 = "UPDATE barang SET JUMLAHBARANG= '"+hasil+"' WHERE IDBARANG='"+nomorBX.getText()+"'";
            pstat = con.prepareStatement(sql2);
            pstat.execute();
            stat.executeUpdate(SQL);
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void namaPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPembayaranActionPerformed
        // TODO add your handling code here:
        int nomor = namaPembayaran.getSelectedIndex();
            nomorPem.setText(String.valueOf(nomor));
        

    }//GEN-LAST:event_namaPembayaranActionPerformed

    private void namaMerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaMerekActionPerformed
        // TODO add your handling code here:
        total.setText(null);
        int nomor = namaMerek.getSelectedIndex();
            nomorMerek.setText(String.valueOf(1+nomor));
            namaBarang.setSelectedItem(null);
            
            try {
            namaBarang.removeAllItems();
          pstat= con.prepareStatement("SELECT NAMABARANG FROM barang WHERE IDMEREK=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, nomorMerek.getText());
           rs = pstat.executeQuery();
           while (rs.next()){
                 namaBarang.addItem(rs.getString("NAMABARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }  
            
             
    }//GEN-LAST:event_namaMerekActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Pelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
          if ("Super Admin".equals(hakAksesAdminSET) || "Admin".equals(hakAksesAdminSET) || "Karyawan Tetap".equals(hakAksesKaryawan) || "Magang".equals(hakAksesKaryawan)) {
            new main().setVisible(true);
            this.dispose();
        } else if (!"Super Admin".equals(hakAksesAdminSET) || !"Admin".equals(hakAksesAdminSET) || !"Karyawan Tetap".equals(hakAksesKaryawan) || !"Magang".equals(hakAksesKaryawan)) {
            new main().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_kembaliActionPerformed

    private void namaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaBarangActionPerformed
        // TODO add your handling code here:
        total.setText(null);
        
      
          
    }//GEN-LAST:event_namaBarangActionPerformed

    private void namaBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaBarangMouseClicked
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
           
    }//GEN-LAST:event_namaBarangMouseClicked

    private void namaBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaBarangMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaBarangMouseExited

    private void namaBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaBarangMouseEntered
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_namaBarangMouseEntered

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
        
       
       
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseExited

    private void namaBarangPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_namaBarangPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaBarangPropertyChange

    private void namaBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaBarangKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaBarangKeyReleased

    private void namaMerekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaMerekMouseClicked
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_namaMerekMouseClicked

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseMoved

    private void namaMerekMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaMerekMouseEntered
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_namaMerekMouseEntered

    private void namaMerekMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaMerekMouseExited
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_namaMerekMouseExited

    private void namaBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaBarangMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaBarangMousePressed

    private void namaMerekMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaMerekMouseMoved
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_namaMerekMouseMoved

    private void namaMerekItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_namaMerekItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaMerekItemStateChanged

    private void hargaBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hargaBarangMouseEntered
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_hargaBarangMouseEntered

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        Locale localeID = new Locale("in", "ID");
        NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(localeID);
        int x = Integer.parseInt(hargaBarang.getText());
        int y = Integer.parseInt(jumlah.getText());
        int z = x * y;
        
        total.setText(formatRupiah.format(z));
    }//GEN-LAST:event_hitungActionPerformed

    private void hitungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitungMouseEntered
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_hitungMouseEntered

    private void hitungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitungMouseExited
        // TODO add your handling code here:
        hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_hitungMouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_jLabel5MouseExited

    private void jumlahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahMouseClicked

    private void jumlahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahMouseEntered
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_jumlahMouseEntered

    private void jumlahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahMouseExited
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_jumlahMouseExited

    private void totalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalMouseEntered
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_totalMouseEntered

    private void totalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalMouseExited
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_totalMouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
         hargaBarang.setText(null);
       
        try {
          pstat= con.prepareStatement("SELECT HARGABARANG, IDBARANG, JUMLAHBARANG FROM barang WHERE NAMABARANG=?;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
          pstat.setString(1, String.valueOf(namaBarang.getSelectedItem()));
           rs = pstat.executeQuery();
           while (rs.next()){
                 hargaBarang.setText(rs.getString("HARGABARANG"));
                  nomorBX.setText(rs.getString("IDBARANG"));
                  nomorBX1.setText(rs.getString("JUMLAHBARANG"));
            }
            rs.last();
          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
          }
    }//GEN-LAST:event_jButton3MouseEntered

    private void nomorBXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorBXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorBXActionPerformed

    private void nomorBX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorBX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorBX1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargaBarang;
    private javax.swing.JButton hitung;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton kembali;
    private javax.swing.JComboBox<String> namaBarang;
    private javax.swing.JComboBox<String> namaMerek;
    private javax.swing.JTextField namaPelanggan;
    private javax.swing.JComboBox<String> namaPembayaran;
    private javax.swing.JTextField namabarangx;
    private javax.swing.JTextField nomorBX;
    private javax.swing.JTextField nomorBX1;
    private javax.swing.JTextField nomorMerek;
    private javax.swing.JTextField nomorPem;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
